
import Sticker_BL1 from '../assets/sticker/BrandLogo/logo_1.svg'
import Sticker_BL2 from '../assets/sticker/BrandLogo/logo_2.svg'
import Sticker_BL3 from '../assets/sticker/BrandLogo/logo_3.svg'
import Sticker_BL4 from '../assets/sticker/BrandLogo/logo_4.svg'
import Sticker_BL5 from '../assets/sticker/BrandLogo/logo_5.svg'
import Sticker_BL6 from '../assets/sticker/BrandLogo/logo_6.svg'

import Ill_1 from '../assets/sticker/Illust/Ill_1.svg'
import Ill_2 from '../assets/sticker/Illust/Ill_2.svg'
import Ill_3 from '../assets/sticker/Illust/Ill_3.svg'
import Ill_4 from '../assets/sticker/Illust/Ill_4.svg'
import Ill_5 from '../assets/sticker/Illust/Ill_5.svg'
import Ill_6 from '../assets/sticker/Illust/Ill_6.svg'
import Ill_7 from '../assets/sticker/Illust/Ill_7.svg'
import Ill_8 from '../assets/sticker/Illust/Ill_8.svg'
import Ill_9 from '../assets/sticker/Illust/Ill_9.svg'
import Ill_10 from '../assets/sticker/Illust/Ill_10.svg'
import Ill_11 from '../assets/sticker/Illust/Ill_11.svg'
import Ill_12 from '../assets/sticker/Illust/Ill_12.svg'
import Ill_13 from '../assets/sticker/Illust/Ill_13.svg'
import Ill_14 from '../assets/sticker/Illust/Ill_14.svg'
import Ill_15 from '../assets/sticker/Illust/Ill_15.svg'
import Ill_16 from '../assets/sticker/Illust/Ill_16.svg'
import Ill_17 from '../assets/sticker/Illust/Ill_17.svg'
import Ill_18 from '../assets/sticker/Illust/Ill_18.svg'
import Ill_B1 from '../assets/sticker/Illust/Ill_B1.svg'
import Ill_B2 from '../assets/sticker/Illust/Ill_B2.svg'
import Ill_B3 from '../assets/sticker/Illust/Ill_B3.svg'

import BodyTp_1 from '../assets/sticker/BodyTp/body_1.svg'
import BodyTp_2 from '../assets/sticker/BodyTp/body_2.svg'
import BodyTp_3 from '../assets/sticker/BodyTp/body_3.svg'
import BodyTp_4 from '../assets/sticker/BodyTp/body_4.svg'
import BodyTp_5 from '../assets/sticker/BodyTp/body_5.svg'
import BodyTp_6 from '../assets/sticker/BodyTp/body_6.svg'
import BodyTp_7 from '../assets/sticker/BodyTp/body_7.svg'
import BodyTp_8 from '../assets/sticker/BodyTp/body_8.svg'
import BodyTp_9 from '../assets/sticker/BodyTp/body_9.svg'

import HeadTp_1 from '../assets/sticker/HeadTp/head_1.svg'
import HeadTp_2 from '../assets/sticker/HeadTp/head_2.svg'
import HeadTp_3 from '../assets/sticker/HeadTp/head_3.svg'
import HeadTp_4 from '../assets/sticker/HeadTp/head_4.svg'
import HeadTp_5 from '../assets/sticker/HeadTp/head_5.svg'
import HeadTp_6 from '../assets/sticker/HeadTp/head_6.svg'

import ele_1 from '../assets/sticker/ele/ele_1.svg'
import ele_2 from '../assets/sticker/ele/ele_2.svg'
import ele_3 from '../assets/sticker/ele/ele_3.svg'
import ele_4 from '../assets/sticker/ele/ele_4.svg'
import ele_5 from '../assets/sticker/ele/ele_5.svg'
import ele_6 from '../assets/sticker/ele/ele_6.svg'
import ele_7 from '../assets/sticker/ele/ele_7.svg'
import ele_8 from '../assets/sticker/ele/ele_8.svg'
import ele_9 from '../assets/sticker/ele/ele_9.svg'
import ele_10 from '../assets/sticker/ele/ele_10.svg'
import ele_11 from '../assets/sticker/ele/ele_11.svg'
import ele_12 from '../assets/sticker/ele/ele_12.svg'
import ele_13 from '../assets/sticker/ele/ele_13.svg'
import ele_14 from '../assets/sticker/ele/ele_14.svg'
import ele_15 from '../assets/sticker/ele/ele_15.svg'
import ele_16 from '../assets/sticker/ele/ele_16.svg'
import ele_17 from '../assets/sticker/ele/ele_17.svg'
import ele_18 from '../assets/sticker/ele/ele_18.svg'

export {
    Sticker_BL1, Sticker_BL2, Sticker_BL3, Sticker_BL4, Sticker_BL5, Sticker_BL6,
    ele_1, ele_2, ele_3, ele_4, ele_5, ele_6, ele_7, ele_8, ele_9, ele_10, ele_11, ele_12, ele_13, ele_14, ele_15, ele_16, ele_17, ele_18,
    Ill_1 , Ill_2 ,Ill_3 ,Ill_4 ,Ill_5 ,Ill_6 ,Ill_7 ,Ill_8 ,Ill_9 ,Ill_10,Ill_11,Ill_12,Ill_13,Ill_14,Ill_15,Ill_16,Ill_17,Ill_18,Ill_B1,Ill_B2,Ill_B3,
    BodyTp_1 ,BodyTp_2, BodyTp_3, BodyTp_4, BodyTp_5, BodyTp_6, BodyTp_7, BodyTp_8, BodyTp_9,
    HeadTp_1, HeadTp_2, HeadTp_3, HeadTp_4, HeadTp_5, HeadTp_6
}